language: python
python:
  - '3.7'
install:
  - pip install --upgrade pip
  - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off -r dev-requirements.txt

script:
  - pytest
  - pycodestyle --max-line-length=80 --count --statistics .
  - mypy main.py --disallow-incomplete-defs
  - mypy controller.py --disallow-incomplete-defs
  - mypy model --disallow-incomplete-defs
  - mypy utils --disallow-incomplete-defs
  - mypy view --disallow-incomplete-defs